# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tomatoWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tomatoWindow(object):
  def setupUi(self, tomatoWindow):
    tomatoWindow.setObjectName("tomatoWindow")
    tomatoWindow.resize(505, 690)
    self.centralwidget = QtWidgets.QWidget(tomatoWindow)
    self.centralwidget.setObjectName("centralwidget")
    self.listView = QtWidgets.QListView(self.centralwidget)
    self.listView.setGeometry(QtCore.QRect(-5, -9, 511, 701))
    self.listView.setStyleSheet("border-image:url(:/background/resource/background/bg9.jpg)")
    self.listView.setObjectName("listView")
    self.tomato10 = QtWidgets.QRadioButton(self.centralwidget)
    self.tomato10.setGeometry(QtCore.QRect(140, 250, 100, 40))
    self.tomato10.setStyleSheet("background-color:white;\n"
"border-radius:20px;\n"
"border:2px solid rgb(255, 255, 0);\n"
"")
    self.tomato10.setObjectName("tomato10")
    self.tomato20 = QtWidgets.QRadioButton(self.centralwidget)
    self.tomato20.setGeometry(QtCore.QRect(270, 250, 100, 40))
    self.tomato20.setStyleSheet("background-color:white;\n"
"border-radius:20px;\n"
"border:2px solid rgb(255, 255, 0);\n"
"")
    self.tomato20.setObjectName("tomato20")
    self.tomato30 = QtWidgets.QRadioButton(self.centralwidget)
    self.tomato30.setGeometry(QtCore.QRect(140, 320, 100, 40))
    self.tomato30.setStyleSheet("background-color:white;\n"
"border-radius:20px;\n"
"border:2px solid rgb(255, 255, 0);\n"
"")
    self.tomato30.setObjectName("tomato30")
    self.tomato45 = QtWidgets.QRadioButton(self.centralwidget)
    self.tomato45.setGeometry(QtCore.QRect(270, 320, 100, 40))
    self.tomato45.setStyleSheet("background-color:white;\n"
"border-radius:20px;\n"
"border:2px solid rgb(255, 255, 0);\n"
"")
    self.tomato45.setObjectName("tomato45")
    self.startTomato = QtWidgets.QPushButton(self.centralwidget)
    self.startTomato.setGeometry(QtCore.QRect(120, 450, 251, 91))
    font = QtGui.QFont()
    font.setFamily("Gadugi")
    font.setPointSize(15)
    self.startTomato.setFont(font)
    self.startTomato.setStyleSheet("border-radius:30px;\n"
"border:2px solid rgb(255, 255, 0);\n"
"")
    self.startTomato.setObjectName("startTomato")
    self.tomatoTimeBoard = QtWidgets.QLabel(self.centralwidget)
    self.tomatoTimeBoard.setGeometry(QtCore.QRect(130, 60, 311, 151))
    font = QtGui.QFont()
    font.setFamily("Arial Rounded MT Bold")
    font.setPointSize(50)
    self.tomatoTimeBoard.setFont(font)
    self.tomatoTimeBoard.setObjectName("tomatoTimeBoard")
    self.editTomato = QtWidgets.QSpinBox(self.centralwidget)
    self.editTomato.setGeometry(QtCore.QRect(260, 390, 111, 41))
    self.editTomato.setStyleSheet("background-color:white;\n"
"border-radius:20px;\n"
"border:2px solid rgb(255, 255, 0);\n"
"")
    self.editTomato.setObjectName("editTomato")
    self.label = QtWidgets.QLabel(self.centralwidget)
    self.label.setGeometry(QtCore.QRect(130, 390, 111, 41))
    self.label.setStyleSheet("background-color:white;\n"
"border-radius:20px;\n"
"border:2px solid rgb(255, 255, 0);\n"
"")
    self.label.setLineWidth(0)
    self.label.setObjectName("label")
    tomatoWindow.setCentralWidget(self.centralwidget)

    self.retranslateUi(tomatoWindow)
    QtCore.QMetaObject.connectSlotsByName(tomatoWindow)

  def retranslateUi(self, tomatoWindow):
    _translate = QtCore.QCoreApplication.translate
    tomatoWindow.setWindowTitle(_translate("tomatoWindow", "MainWindow"))
    self.tomato10.setText(_translate("tomatoWindow", "10分钟"))
    self.tomato20.setText(_translate("tomatoWindow", "20分钟"))
    self.tomato30.setText(_translate("tomatoWindow", "30分钟"))
    self.tomato45.setText(_translate("tomatoWindow", "45分钟"))
    self.startTomato.setText(_translate("tomatoWindow", "Start or Pause"))
    self.tomatoTimeBoard.setText(_translate("tomatoWindow", "00:00"))
    self.label.setText(_translate("tomatoWindow", "自定义时间"))
import resource_rc


if __name__ == "__main__":
  import sys
  app = QtWidgets.QApplication(sys.argv)
  tomatoWindow = QtWidgets.QMainWindow()
  ui = Ui_tomatoWindow()
  ui.setupUi(tomatoWindow)
  tomatoWindow.show()
  sys.exit(app.exec_())
