# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'taskCreator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_createTaskDialog(object):
  def setupUi(self, createTaskDialog):
    createTaskDialog.setObjectName("createTaskDialog")
    createTaskDialog.resize(478, 240)
    self.buttonBox = QtWidgets.QDialogButtonBox(createTaskDialog)
    self.buttonBox.setGeometry(QtCore.QRect(100, 350, 171, 32))
    self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
    self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
    self.buttonBox.setObjectName("buttonBox")
    self.listView = QtWidgets.QListView(createTaskDialog)
    self.listView.setGeometry(QtCore.QRect(-10, 0, 491, 251))
    font = QtGui.QFont()
    font.setPointSize(15)
    self.listView.setFont(font)
    self.listView.setStyleSheet("border-image:url(:/background/resource/background/bg5.jpg)")
    self.listView.setObjectName("listView")
    self.formLayoutWidget = QtWidgets.QWidget(createTaskDialog)
    self.formLayoutWidget.setGeometry(QtCore.QRect(180, 20, 261, 211))
    self.formLayoutWidget.setObjectName("formLayoutWidget")
    self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
    self.formLayout.setContentsMargins(0, 0, 0, 0)
    self.formLayout.setObjectName("formLayout")
    self.label = QtWidgets.QLabel(self.formLayoutWidget)
    font = QtGui.QFont()
    font.setPointSize(13)
    self.label.setFont(font)
    self.label.setObjectName("label")
    self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
    self.taskName = QtWidgets.QLineEdit(self.formLayoutWidget)
    self.taskName.setObjectName("taskName")
    self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.taskName)
    self.taskKind = QtWidgets.QComboBox(self.formLayoutWidget)
    self.taskKind.setObjectName("taskKind")
    self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.taskKind)
    self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
    font = QtGui.QFont()
    font.setPointSize(13)
    self.label_3.setFont(font)
    self.label_3.setObjectName("label_3")
    self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
    self.taskNote = QtWidgets.QTextEdit(self.formLayoutWidget)
    self.taskNote.setObjectName("taskNote")
    self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.taskNote)
    self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
    font = QtGui.QFont()
    font.setPointSize(13)
    self.label_2.setFont(font)
    self.label_2.setObjectName("label_2")
    self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
    self.sureButton = QtWidgets.QPushButton(createTaskDialog)
    self.sureButton.setGeometry(QtCore.QRect(50, 170, 101, 41))
    font = QtGui.QFont()
    font.setPointSize(13)
    self.sureButton.setFont(font)
    self.sureButton.setObjectName("sureButton")
    self.listView.raise_()
    self.buttonBox.raise_()
    self.formLayoutWidget.raise_()
    self.sureButton.raise_()

    self.retranslateUi(createTaskDialog)
    self.buttonBox.accepted.connect(createTaskDialog.accept) # type: ignore
    self.buttonBox.rejected.connect(createTaskDialog.reject) # type: ignore
    QtCore.QMetaObject.connectSlotsByName(createTaskDialog)

  def retranslateUi(self, createTaskDialog):
    _translate = QtCore.QCoreApplication.translate
    createTaskDialog.setWindowTitle(_translate("createTaskDialog", "Dialog"))
    self.label.setText(_translate("createTaskDialog", "任务名称"))
    self.label_3.setText(_translate("createTaskDialog", "备注"))
    self.label_2.setText(_translate("createTaskDialog", "任务类别"))
    self.sureButton.setText(_translate("createTaskDialog", "确定"))
import resource_rc


if __name__ == "__main__":
  import sys
  app = QtWidgets.QApplication(sys.argv)
  createTaskDialog = QtWidgets.QDialog()
  ui = Ui_createTaskDialog()
  ui.setupUi(createTaskDialog)
  createTaskDialog.show()
  sys.exit(app.exec_())
