# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WelcomeWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WelcomeWindow(object):
  def setupUi(self, WelcomeWindow):
    WelcomeWindow.setObjectName("WelcomeWindow")
    WelcomeWindow.resize(500, 687)
    self.centralwidget = QtWidgets.QWidget(WelcomeWindow)
    self.centralwidget.setObjectName("centralwidget")
    self.listView = QtWidgets.QListView(self.centralwidget)
    self.listView.setGeometry(QtCore.QRect(-10, -50, 511, 741))
    font = QtGui.QFont()
    font.setFamily("Mistral")
    self.listView.setFont(font)
    self.listView.setStyleSheet("border-image:url(:/background/resource/background/bg1.jpg)")
    self.listView.setObjectName("listView")
    self.label = QtWidgets.QLabel(self.centralwidget)
    self.label.setGeometry(QtCore.QRect(20, 250, 231, 121))
    font = QtGui.QFont()
    font.setFamily("Harlow Solid Italic")
    font.setPointSize(40)
    font.setBold(True)
    font.setItalic(True)
    font.setWeight(75)
    self.label.setFont(font)
    self.label.setStyleSheet("color:rgb(255, 255, 255)")
    self.label.setObjectName("label")
    self.label_2 = QtWidgets.QLabel(self.centralwidget)
    self.label_2.setGeometry(QtCore.QRect(20, 390, 361, 71))
    font = QtGui.QFont()
    font.setFamily("Imprint MT Shadow")
    font.setPointSize(35)
    font.setBold(True)
    font.setItalic(True)
    font.setWeight(75)
    self.label_2.setFont(font)
    self.label_2.setStyleSheet("color:rgb(255, 255, 255)")
    self.label_2.setObjectName("label_2")
    self.label_3 = QtWidgets.QLabel(self.centralwidget)
    self.label_3.setGeometry(QtCore.QRect(130, 460, 421, 81))
    font = QtGui.QFont()
    font.setFamily("Impact")
    font.setPointSize(25)
    font.setBold(True)
    font.setItalic(True)
    font.setWeight(75)
    self.label_3.setFont(font)
    self.label_3.setStyleSheet("color:rgb(255, 85, 0)")
    self.label_3.setObjectName("label_3")
    self.label_4 = QtWidgets.QLabel(self.centralwidget)
    self.label_4.setGeometry(QtCore.QRect(100, 520, 321, 191))
    self.label_4.setStyleSheet("border-image:url(:/picture/resource/pic/f915d427c7ce4ae8afb9ab696751defe.ico)")
    self.label_4.setText("")
    self.label_4.setObjectName("label_4")
    self.label_5 = QtWidgets.QLabel(self.centralwidget)
    self.label_5.setGeometry(QtCore.QRect(210, 340, 291, 61))
    font = QtGui.QFont()
    font.setFamily("Harlow Solid Italic")
    font.setPointSize(25)
    font.setBold(True)
    font.setItalic(True)
    font.setWeight(75)
    self.label_5.setFont(font)
    self.label_5.setStyleSheet("color:rgb(255, 255, 255)")
    self.label_5.setObjectName("label_5")
    self.listView.raise_()
    self.label_3.raise_()
    self.label.raise_()
    self.label_4.raise_()
    self.label_2.raise_()
    self.label_5.raise_()
    WelcomeWindow.setCentralWidget(self.centralwidget)

    self.retranslateUi(WelcomeWindow)
    QtCore.QMetaObject.connectSlotsByName(WelcomeWindow)

  def retranslateUi(self, WelcomeWindow):
    _translate = QtCore.QCoreApplication.translate
    WelcomeWindow.setWindowTitle(_translate("WelcomeWindow", "MainWindow"))
    self.label.setText(_translate("WelcomeWindow", "Hello! "))
    self.label_2.setText(_translate("WelcomeWindow", "Minion\'s "))
    self.label_3.setText(_translate("WelcomeWindow", "Time Manager!"))
    self.label_5.setText(_translate("WelcomeWindow", "Welcome to "))
import resource_rc


if __name__ == "__main__":
  import sys
  app = QtWidgets.QApplication(sys.argv)
  WelcomeWindow = QtWidgets.QMainWindow()
  ui = Ui_WelcomeWindow()
  ui.setupUi(WelcomeWindow)
  WelcomeWindow.show()
  sys.exit(app.exec_())
