# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'historyWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HistoryWindow(object):
  def setupUi(self, HistoryWindow):
    HistoryWindow.setObjectName("HistoryWindow")
    HistoryWindow.resize(508, 687)
    self.centralwidget = QtWidgets.QWidget(HistoryWindow)
    self.centralwidget.setObjectName("centralwidget")
    self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
    self.scrollArea.setGeometry(QtCore.QRect(0, 0, 501, 691))
    self.scrollArea.setStyleSheet("")
    self.scrollArea.setWidgetResizable(True)
    self.scrollArea.setObjectName("scrollArea")
    self.scrollAreaWidgetContents = QtWidgets.QWidget()
    self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -911, 482, 1600))
    self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(400, 1600))
    self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
    self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
    self.label.setGeometry(QtCore.QRect(20, 40, 371, 61))
    font = QtGui.QFont()
    font.setPointSize(15)
    self.label.setFont(font)
    self.label.setStyleSheet("border-radius:30px;\n"
"border:2px solid rgb(255, 255, 0);\n"
"")
    self.label.setObjectName("label")
    self.scrollArea_2 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
    self.scrollArea_2.setGeometry(QtCore.QRect(30, 120, 431, 261))
    self.scrollArea_2.setWidgetResizable(True)
    self.scrollArea_2.setObjectName("scrollArea_2")
    self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
    self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1000, 600))
    self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(1000, 600))
    self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
    self.showHistoryLW = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
    self.showHistoryLW.setGeometry(QtCore.QRect(0, 0, 1001, 611))
    self.showHistoryLW.setStyleSheet("")
    self.showHistoryLW.setObjectName("showHistoryLW")
    self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
    self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
    self.label_2.setGeometry(QtCore.QRect(20, 400, 451, 61))
    font = QtGui.QFont()
    font.setPointSize(15)
    self.label_2.setFont(font)
    self.label_2.setStyleSheet("border-radius:30px;\n"
"border:2px solid rgb(255, 255, 0);\n"
"")
    self.label_2.setObjectName("label_2")
    self.scrollArea_3 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
    self.scrollArea_3.setGeometry(QtCore.QRect(30, 480, 431, 261))
    self.scrollArea_3.setWidgetResizable(True)
    self.scrollArea_3.setObjectName("scrollArea_3")
    self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
    self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 412, 500))
    self.scrollAreaWidgetContents_3.setMinimumSize(QtCore.QSize(410, 500))
    self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
    self.historyStatisticLW = QtWidgets.QListWidget(self.scrollAreaWidgetContents_3)
    self.historyStatisticLW.setGeometry(QtCore.QRect(0, 0, 411, 601))
    self.historyStatisticLW.setObjectName("historyStatisticLW")
    self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
    self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
    self.label_3.setGeometry(QtCore.QRect(20, 760, 441, 61))
    font = QtGui.QFont()
    font.setPointSize(15)
    self.label_3.setFont(font)
    self.label_3.setStyleSheet("border-radius:30px;\n"
"border:2px solid rgb(255, 255, 0);\n"
"")
    self.label_3.setObjectName("label_3")
    self.clearHistoryButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
    self.clearHistoryButton.setGeometry(QtCore.QRect(120, 1540, 241, 41))
    font = QtGui.QFont()
    font.setPointSize(15)
    self.clearHistoryButton.setFont(font)
    self.clearHistoryButton.setObjectName("clearHistoryButton")
    self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
    self.label_4.setGeometry(QtCore.QRect(20, 1000, 331, 61))
    font = QtGui.QFont()
    font.setPointSize(15)
    self.label_4.setFont(font)
    self.label_4.setStyleSheet("border-radius:30px;\n"
"border:2px solid rgb(255, 255, 0);\n"
"")
    self.label_4.setObjectName("label_4")
    self.listView = QtWidgets.QListView(self.scrollAreaWidgetContents)
    self.listView.setGeometry(QtCore.QRect(-10, -120, 521, 2021))
    self.listView.setStyleSheet("border-image:url(:/background/resource/background/bg11.jpg)")
    self.listView.setObjectName("listView")
    self.kindTab = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
    self.kindTab.setGeometry(QtCore.QRect(30, 830, 431, 161))
    self.kindTab.setObjectName("kindTab")
    self.plotCanvas = QtWidgets.QLabel(self.scrollAreaWidgetContents)
    self.plotCanvas.setGeometry(QtCore.QRect(30, 1070, 431, 431))
    self.plotCanvas.setText("")
    self.plotCanvas.setObjectName("plotCanvas")
    self.listView.raise_()
    self.label.raise_()
    self.scrollArea_2.raise_()
    self.label_2.raise_()
    self.scrollArea_3.raise_()
    self.label_3.raise_()
    self.clearHistoryButton.raise_()
    self.label_4.raise_()
    self.kindTab.raise_()
    self.plotCanvas.raise_()
    self.scrollArea.setWidget(self.scrollAreaWidgetContents)
    HistoryWindow.setCentralWidget(self.centralwidget)

    self.retranslateUi(HistoryWindow)
    QtCore.QMetaObject.connectSlotsByName(HistoryWindow)

  def retranslateUi(self, HistoryWindow):
    _translate = QtCore.QCoreApplication.translate
    HistoryWindow.setWindowTitle(_translate("HistoryWindow", "MainWindow"))
    self.label.setText(_translate("HistoryWindow", "历史记录查看"))
    self.label_2.setText(_translate("HistoryWindow", "历史记录统计-按日期分类"))
    self.label_3.setText(_translate("HistoryWindow", "历史记录统计-按任务类别分类"))
    self.clearHistoryButton.setText(_translate("HistoryWindow", "清空历史记录"))
    self.label_4.setText(_translate("HistoryWindow", "分类记录统计与饼图"))
import resource_rc


if __name__ == "__main__":
  import sys
  app = QtWidgets.QApplication(sys.argv)
  HistoryWindow = QtWidgets.QMainWindow()
  ui = Ui_HistoryWindow()
  ui.setupUi(HistoryWindow)
  HistoryWindow.show()
  sys.exit(app.exec_())
