# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
  def setupUi(self, MainWindow):
    MainWindow.setObjectName("MainWindow")
    MainWindow.resize(500, 687)
    self.centralwidget = QtWidgets.QWidget(MainWindow)
    self.centralwidget.setObjectName("centralwidget")
    self.listView = QtWidgets.QListView(self.centralwidget)
    self.listView.setGeometry(QtCore.QRect(0, -40, 501, 731))
    self.listView.setStyleSheet("border-image:url(:/background/resource/background/bg11.jpg)")
    self.listView.setObjectName("listView")
    self.startTiming = QtWidgets.QPushButton(self.centralwidget)
    self.startTiming.setGeometry(QtCore.QRect(50, 450, 121, 71))
    font = QtGui.QFont()
    font.setFamily("Gadugi")
    font.setPointSize(12)
    font.setBold(True)
    self.startTiming.setFont(font)
    self.startTiming.setStyleSheet("border-radius:30px;\n"
"border:2px solid rgb(255, 255, 0);\n"
"")
    self.startTiming.setObjectName("startTiming")
    self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
    self.horizontalLayoutWidget.setGeometry(QtCore.QRect(18, 605, 461, 71))
    self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
    self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
    self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
    self.horizontalLayout.setObjectName("horizontalLayout")
    self.callTomatoWindowButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
    font = QtGui.QFont()
    font.setFamily("Bahnschrift")
    font.setPointSize(10)
    font.setBold(True)
    font.setItalic(False)
    self.callTomatoWindowButton.setFont(font)
    self.callTomatoWindowButton.setStyleSheet("background-color:yellow;\n"
"border-radius:30px;\n"
"border:2px solid rgb(255, 255, 0);")
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap(":/picture/resource/pic/4.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.callTomatoWindowButton.setIcon(icon)
    self.callTomatoWindowButton.setIconSize(QtCore.QSize(60, 60))
    self.callTomatoWindowButton.setObjectName("callTomatoWindowButton")
    self.horizontalLayout.addWidget(self.callTomatoWindowButton)
    self.callTaskWIndowButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
    font = QtGui.QFont()
    font.setFamily("Bahnschrift")
    font.setPointSize(10)
    font.setBold(True)
    font.setItalic(False)
    self.callTaskWIndowButton.setFont(font)
    self.callTaskWIndowButton.setStyleSheet("background-color:rgb(255, 170, 0);\n"
"border-radius:30px;\n"
"border:2px solid rgb(255, 170, 0);\n"
"")
    icon1 = QtGui.QIcon()
    icon1.addPixmap(QtGui.QPixmap(":/picture/resource/pic/8.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.callTaskWIndowButton.setIcon(icon1)
    self.callTaskWIndowButton.setIconSize(QtCore.QSize(60, 60))
    self.callTaskWIndowButton.setObjectName("callTaskWIndowButton")
    self.horizontalLayout.addWidget(self.callTaskWIndowButton)
    self.readHistoryButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
    font = QtGui.QFont()
    font.setFamily("Bahnschrift")
    font.setPointSize(8)
    font.setBold(True)
    font.setItalic(False)
    self.readHistoryButton.setFont(font)
    self.readHistoryButton.setStyleSheet("background-color:yellow;\n"
"border-radius:30px;\n"
"border:2px solid rgb(255, 255, 0);\n"
"")
    icon2 = QtGui.QIcon()
    icon2.addPixmap(QtGui.QPixmap(":/picture/resource/pic/5.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.readHistoryButton.setIcon(icon2)
    self.readHistoryButton.setIconSize(QtCore.QSize(60, 60))
    self.readHistoryButton.setObjectName("readHistoryButton")
    self.horizontalLayout.addWidget(self.readHistoryButton)
    self.label_6 = QtWidgets.QLabel(self.centralwidget)
    self.label_6.setGeometry(QtCore.QRect(140, 80, 231, 241))
    self.label_6.setStyleSheet("border-image:url(:/picture/resource/pic/2.ico)")
    self.label_6.setText("")
    self.label_6.setObjectName("label_6")
    self.label_2 = QtWidgets.QLabel(self.centralwidget)
    self.label_2.setGeometry(QtCore.QRect(160, 20, 191, 111))
    self.label_2.setStyleSheet("border-image:url(:/icon/resource/icon/2.ico)")
    self.label_2.setText("")
    self.label_2.setObjectName("label_2")
    self.Timer = QtWidgets.QLabel(self.centralwidget)
    self.Timer.setGeometry(QtCore.QRect(40, 290, 421, 151))
    font = QtGui.QFont()
    font.setFamily("Arial Rounded MT Bold")
    font.setPointSize(50)
    self.Timer.setFont(font)
    self.Timer.setObjectName("Timer")
    self.endTaskButton = QtWidgets.QPushButton(self.centralwidget)
    self.endTaskButton.setGeometry(QtCore.QRect(200, 450, 121, 71))
    font = QtGui.QFont()
    font.setFamily("Franklin Gothic Demi")
    font.setPointSize(12)
    font.setBold(True)
    self.endTaskButton.setFont(font)
    self.endTaskButton.setStyleSheet("border-radius:30px;\n"
"border:2px solid rgb(255, 255, 0);\n"
"")
    self.endTaskButton.setObjectName("endTaskButton")
    self.resetButton = QtWidgets.QPushButton(self.centralwidget)
    self.resetButton.setGeometry(QtCore.QRect(350, 450, 121, 71))
    font = QtGui.QFont()
    font.setFamily("Franklin Gothic Demi")
    font.setPointSize(12)
    font.setBold(True)
    self.resetButton.setFont(font)
    self.resetButton.setStyleSheet("border-radius:30px;\n"
"border:2px solid rgb(255, 255, 0);\n"
"")
    self.resetButton.setObjectName("resetButton")
    MainWindow.setCentralWidget(self.centralwidget)

    self.retranslateUi(MainWindow)
    QtCore.QMetaObject.connectSlotsByName(MainWindow)

  def retranslateUi(self, MainWindow):
    _translate = QtCore.QCoreApplication.translate
    MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
    self.startTiming.setText(_translate("MainWindow", "开始/暂停"))
    self.callTomatoWindowButton.setText(_translate("MainWindow", "番茄钟"))
    self.callTaskWIndowButton.setText(_translate("MainWindow", "任务"))
    self.readHistoryButton.setText(_translate("MainWindow", "历史"))
    self.Timer.setText(_translate("MainWindow", "00:00:00"))
    self.endTaskButton.setText(_translate("MainWindow", "结束任务"))
    self.resetButton.setText(_translate("MainWindow", "归零"))
import resource_rc


if __name__ == "__main__":
  import sys
  app = QtWidgets.QApplication(sys.argv)
  MainWindow = QtWidgets.QMainWindow()
  ui = Ui_MainWindow()
  ui.setupUi(MainWindow)
  MainWindow.show()
  sys.exit(app.exec_())
