# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'taskWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_taskWindow(object):
  def setupUi(self, taskWindow):
    taskWindow.setObjectName("taskWindow")
    taskWindow.resize(500, 687)
    self.centralwidget = QtWidgets.QWidget(taskWindow)
    self.centralwidget.setObjectName("centralwidget")
    self.listView = QtWidgets.QListView(self.centralwidget)
    self.listView.setGeometry(QtCore.QRect(0, -10, 511, 771))
    self.listView.setStyleSheet("border-image:url(:/background/resource/background/bg10.jpg)")
    self.listView.setObjectName("listView")
    self.createTaskButton = QtWidgets.QPushButton(self.centralwidget)
    self.createTaskButton.setGeometry(QtCore.QRect(190, 30, 121, 51))
    font = QtGui.QFont()
    font.setFamily("Microsoft Yi Baiti")
    font.setPointSize(12)
    self.createTaskButton.setFont(font)
    self.createTaskButton.setStyleSheet("border-radius:30px;\n"
"border:2px solid rgb(255, 255, 0);\n"
"")
    self.createTaskButton.setObjectName("createTaskButton")
    self.taskTab = QtWidgets.QTabWidget(self.centralwidget)
    self.taskTab.setGeometry(QtCore.QRect(20, 110, 451, 461))
    self.taskTab.setObjectName("taskTab")
    self.createTabButton = QtWidgets.QPushButton(self.centralwidget)
    self.createTabButton.setGeometry(QtCore.QRect(360, 590, 131, 51))
    font = QtGui.QFont()
    font.setPointSize(9)
    self.createTabButton.setFont(font)
    self.createTabButton.setStyleSheet("border-radius:30px;\n"
"border:2px solid rgb(255, 255, 0);\n"
"")
    self.createTabButton.setObjectName("createTabButton")
    self.delTaskButton = QtWidgets.QPushButton(self.centralwidget)
    self.delTaskButton.setGeometry(QtCore.QRect(20, 600, 101, 41))
    self.delTaskButton.setStyleSheet("border-radius:30px;\n"
"border:2px solid rgb(255, 255, 0);\n"
"")
    self.delTaskButton.setObjectName("delTaskButton")
    self.startTaskButton = QtWidgets.QPushButton(self.centralwidget)
    self.startTaskButton.setGeometry(QtCore.QRect(40, 30, 121, 51))
    font = QtGui.QFont()
    font.setFamily("Microsoft Yi Baiti")
    font.setPointSize(12)
    self.startTaskButton.setFont(font)
    self.startTaskButton.setStyleSheet("border-radius:30px;\n"
"border:2px solid rgb(255, 255, 0);\n"
"")
    self.startTaskButton.setObjectName("startTaskButton")
    taskWindow.setCentralWidget(self.centralwidget)

    self.retranslateUi(taskWindow)
    self.taskTab.setCurrentIndex(-1)
    QtCore.QMetaObject.connectSlotsByName(taskWindow)

  def retranslateUi(self, taskWindow):
    _translate = QtCore.QCoreApplication.translate
    taskWindow.setWindowTitle(_translate("taskWindow", "MainWindow"))
    self.createTaskButton.setText(_translate("taskWindow", "创建任务"))
    self.taskTab.setWhatsThis(_translate("taskWindow", "<html><head/><body><p>mK</p></body></html>"))
    self.createTabButton.setText(_translate("taskWindow", "创建新的分类"))
    self.delTaskButton.setText(_translate("taskWindow", "删除"))
    self.startTaskButton.setText(_translate("taskWindow", "开始任务"))
import resource_rc


if __name__ == "__main__":
  import sys
  app = QtWidgets.QApplication(sys.argv)
  taskWindow = QtWidgets.QMainWindow()
  ui = Ui_taskWindow()
  ui.setupUi(taskWindow)
  taskWindow.show()
  sys.exit(app.exec_())
